# Day_3_1 Study CNN Pytorch modules
- Deep Learning과 Convolution Neural Network과 관련한 Pytorch modules에 대해 실습

![image.png](http://drive.google.com/uc?id=1xSFMz26Z14rldETZG4nXDPq_ZZKK2ISF)

![image.png](http://drive.google.com/uc?id=13WyqK4RTceUmGKL6_Iwgz_2sShX2pVGC)

![image.png](http://drive.google.com/uc?id=1eBPt8_ZfJrG-PrYMffXb_DpaPRutK9jh)

![image.png](http://drive.google.com/uc?id=1PsSApUabTfSseQMH2vLyZKtx9fMJ6fA1)

## 1) nn.Conv2d
- 2-dim 데이터에 하나의 Convolution layer를 생성
- 필요한 하이퍼파라미터를 설정하면 Convolution layer에 필요한 parameter weight를 자동으로 선언
- `Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')`
### parameters
  - in_channels: 입력 채널 수. 흑백 이미지일 경우 1, RGB 값을 가진 이미지일 경우 3
  - out_channels: 출력 채널 수
  - kernel_size: 커널 사이즈
  - stride: stride 사이즈
  - padding: padding 사이즈
### shape
1. Input tensor($N, C_{in}, H_{in}, W_{in}$)
 - $N$: batch의 크기
 - $C_{in}$ : `in_channerls`에 넣은 값과 일치해야 함.
 - $H_{in}$ : 2D input tensor의 높이
 - $ W_{in}$:  2D input tensor의 너비


- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html)

![image.png](http://drive.google.com/uc?id=18ZaNZcwh4SOBSa8WmXtGgQM4iDi6q6F5)

In [1]:
import torch
import torch.nn as nn

### Example 1) kernel_size=3, stride=1, padding=0
![image.png](http://drive.google.com/uc?id=1dvnKVDptCOD1VLtiiTztOB2Lp4SAkuOE)

In [2]:
input = torch.ones(1,1,4,4)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


### Example 2) kernel_size=3, stride=2, padding=0
![image.png](http://drive.google.com/uc?id=1SgTHZ4mGkQgaHmpVNi-IcHqP1pW5Crm0)

In [3]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


### Example 3) kernel_size=4, stride=1, padding=2
![image.png](http://drive.google.com/uc?id=1jA5h5lM6mbMtRtBT8rRFacf6yQazmHzW)


In [4]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=4, stride=1, padding=2)
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 6, 6])


### Excercise 1) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1uAgXHskAXGtdowxGKw99Dtw4n4f_X34s)


In [5]:
input = torch.ones(1,1,6,6)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 3, 3])


### Excercise 2) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1Q2WLIYER2T5h8Pri9diRs3J_Kmjb7MXo)


In [6]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 5, 5])


### Excercise 3) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=15MRDXon_68pySZHQy9wBqdbwp8HQNdv8)


In [7]:


input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 3, 3])


### Excercise 4) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=17yCuQSaW2Q0XUwwHG8tBvts15Y-U3we1)

In [8]:
input = torch.ones(1,1,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=2)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 7, 7])


### Excercise 5) kernel_size=?, stride=?, padding=?
![image.png](http://drive.google.com/uc?id=1fNZTyHOtHX0y7sFW-e6tx0qP8mrQ7wK8)

In [9]:
input = torch.ones(1,3,5,5)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=3, out_channels=2, kernel_size=3, stride=2, padding=1)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 2, 3, 3])


### Excercise 6) Input size=(7,7), kernel_size=3, stride=2, padding=0, Output size=?
![image.png](http://drive.google.com/uc?id=1d9C1FkXHRwx86OfBZ2-1XrIVyak_skMG)

In [10]:
input = torch.ones(1,1,6,6)
########################################## Complete This Code~!
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)
########################################## Complete This Code~!
output = conv_layer(input)
print(output.shape)

torch.Size([1, 1, 2, 2])


## < Convolution output feature map size 계산 >
![image.png](http://drive.google.com/uc?id=12reHf9xtapZrVBG4LlNbNGa37ZeFfUqk)
![image.png](http://drive.google.com/uc?id=1iqd-9-hHgnc6Zz7kR6v9EMhLWrMmY07N)

In [11]:
# 예제 1)
########################################## Complete This Code~!
ans_1 = int( (227 - 11 + 2*0) / 4 + 1 )
########################################## Complete This Code~!
print(f'예제 1 정답 : {ans_1}')

# 예제 2)
ans_2 = int( (64 - 7 + 2*0) / 2 + 1 )
print(f'예제 2 정답 : {ans_2}') # 28.5 + 1 => 29

# 예제 3)
########################################## Complete This Code~!
ans_3 = int( (32 - 5 + 2*2) / 1 + 1 )
########################################## Complete This Code~!
print(f'예제 3 정답 : {ans_3}')

# 예제 4)
# <Height>
ans_4_height = int( (32 - 5 + 2*0) / 1 + 1 )
# <Width>
ans_4_width = int( (64 - 5 + 2*0) / 1 + 1 )
print(f'예제 4 정답 : ({ans_4_height}, {ans_4_width})') # (28, 60)

# 예제 5)
# <Height>
########################################## Complete This Code~!
ans_5_height = int((64 - 3 + 2 * 1) + 1)
########################################## Complete This Code~!
#<Width>
########################################## Complete This Code~!
ans_5_width = int((32 - 3 + 2 * 1) + 1)
########################################## Complete This Code~!
print(f'예제 5 정답 : ({ans_5_height}, {ans_5_width})')

예제 1 정답 : 55
예제 2 정답 : 29
예제 3 정답 : 32
예제 4 정답 : (28, 60)
예제 5 정답 : (64, 32)


In [12]:
# 각 예제에 맞게 INPUT 값을 바꾸어 설정할 수 있습니다.
INPUT_SIZE = (227,227)
IN_CHANNELS = 3
OUT_CHANNELS = 10
KERNEL_SIZE = 11
STRIDE = 4
PADDING = 0

input = torch.ones(1,IN_CHANNELS,INPUT_SIZE[0],INPUT_SIZE[1])
func = nn.Conv2d(in_channels=IN_CHANNELS, out_channels=OUT_CHANNELS, kernel_size=KERNEL_SIZE, stride=STRIDE, padding=PADDING)
output = func(input)
print(output.shape)

torch.Size([1, 10, 55, 55])


## 2) nn.MaxPool2d
- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html)

![image.png](http://drive.google.com/uc?id=1010fN_7lMHuxmda3_gdSxfbW36yTC6F5)
![image.png](http://drive.google.com/uc?id=1D2e9iFzJZMPLxRYucC4LS2B44-a3dlQk)

![image.png](http://drive.google.com/uc?id=1xEmoXL-lmanXO6eSYDEmq7_cyFB73dRF)

In [13]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])


In [14]:
func = nn.MaxPool2d(kernel_size=2)
output = func(input)
print(output)

tensor([[[6., 8.],
         [3., 4.]]])


## 3) nn.AvgPool2d
- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html)

![image.png](http://drive.google.com/uc?id=1z4OjHBduieJQVJqquISgrsmVqlVlfgS1)
![image.png](http://drive.google.com/uc?id=10U4Z4OGKSWQHeDMa-f9KRnUXhfGKhKnk)

![image.png](http://drive.google.com/uc?id=1wg2vJ8t780P6l5EUw1oLF3QTSjZBse0a)


In [15]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])


In [16]:
func = nn.AvgPool2d(kernel_size=4)
output = func(input)
print(output)

tensor([[[2.7500]]])


## 4) nn.AdaptiveAvgPool2d()
- kernel_size, stride, padding을 입력하는 대신에 output의 사이즈를 입력
-  위의 식에 따라서 자동으로 kernel_size, stride, padding이 결정되어 pooling을 할 수 있음.
- 즉, Average Pooling을 할 때, 출력 크기 조절하기가 상당히 쉬워짐

- [doc] (https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html)

![image.png](http://drive.google.com/uc?id=190yR-M7yTb6ZlILOi4J5RSrfLeh_iul8)

![image.png](http://drive.google.com/uc?id=1KMgjceD4tsS67kUvAb1BYC29HXWJb0Hr)


In [17]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]]) # shpae : [1,4,4]
print(input)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])


In [18]:
func = nn.AdaptiveAvgPool2d(1) # (1, 1)
output = func(input)
print(output) # shape : [1,1,1]

tensor([[[2.7500]]])


In [19]:
input = torch.randn((1,3,4,4))
print(input)

tensor([[[[ 1.3303,  1.2775, -0.6692,  1.8393],
          [-1.1082,  0.4654,  2.5273,  0.2901],
          [ 0.2338,  0.3129, -0.9644,  1.0904],
          [ 1.2694, -0.9081,  0.0344,  0.6271]],

         [[ 1.6073,  0.7225, -0.7628, -0.6569],
          [ 0.0733,  0.0755,  2.2070,  0.9038],
          [-2.0146, -0.6650, -0.2965,  0.3387],
          [-0.5523, -0.8011,  0.0403,  0.2335]],

         [[-0.0650, -0.3144,  1.1845,  0.7462],
          [-0.3355,  0.5643, -1.5725, -0.6280],
          [-0.6495,  0.3732,  0.3369, -0.9877],
          [ 0.9708, -1.0790, -0.8737, -0.5862]]]])


In [20]:
func = nn.AdaptiveAvgPool2d(1)
output = func(input)
print(output) # shape : [1,3,1,1]

tensor([[[[ 0.4780]],

         [[ 0.0283]],

         [[-0.1822]]]])


In [21]:
input = torch.randn((1,3,1,1))
print(input)

tensor([[[[ 0.8692]],

         [[ 1.0536]],

         [[-2.1466]]]])


In [22]:
func = nn.AdaptiveAvgPool2d(7) # (7, 7)
output = func(input)
print(output) # shape : [1,3,7,7]

tensor([[[[ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692],
          [ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692],
          [ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692],
          [ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692],
          [ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692],
          [ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692],
          [ 0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692,  0.8692]],

         [[ 1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536],
          [ 1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536],
          [ 1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536],
          [ 1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536],
          [ 1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536],
          [ 1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536,  1.0536],
          [ 1.0536,  1.